spring:
  application:
    name: customer-service
  profiles:
    active: development,swagger
  cloud:
    consul:
      host: dockermachine
      port: 8500
      discovery:
        enabled: true
        instanceId: ${spring.application.name}

server:
  port: 8090

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

# To disable Hystrix in Feign
feign:
  accountServiceUrl: http://dockermachine:8080
  hystrix:
    enabled: false

  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
      org.springframework.cloud.consul: DEBUG
